### ISSUE TITLE
Cambio de Tema

### ISSUE THREAD

**Issue by ThaisArm** [Keybrish/ProyectoAppBusesSocio#2]
Se solicita un cambio en la temática de la aplicación (color) ya que esta configurada con el tema por defecto de Android Studio cuando debería ir de acuerdo al branding de la aplicación.

**Comment by Keybrish** [comment]
Ya realicé el cambio, necesito autorización para fusionar los cambios con develop
![image](https://github.com/Keybrish/ProyectoAppBusesSocio/assets/93953328/7f4aef38-4d98-4232-9c12-2912f5805ae3)

**Comment by ThaisArm** [comment]
Gracias por efectuar los cambios, se puede proceder con la fusión de cambios a develop
